version: "3.8"
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - DB_HOST=localhost
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
